require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/migrate/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
    - script/**/*
    - spec/**/**/*
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130
  AllowURI: true

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/forms/**/*'

Rails/I18nLocaleTexts:
  Enabled: false
